In [2]:
#!touch 0-mean_cov.py

In [3]:
!chmod +x *.py

In [497]:
#!/usr/bin/env python3
""" mean cov """
import numpy as np


def mean_cov(X):
    """
    calculate the mean and
    covariance of a data set
    """
    mean = X.mean(axis=0, keepdims=True)
    n = X.shape[0] - 1
    x = X - mean
    cov = np.dot(x.T, X.conj()) / n
    return mean, cov

In [498]:
#!/usr/bin/env python3

if __name__ == '__main__':
    import numpy as np
    #mean_cov = __import__('0-mean_cov').mean_cov

    np.random.seed(0)
    X = np.random.multivariate_normal([12, 30, 10], [[36, -30, 15], [-30, 100, -20], [15, -20, 25]], 10000)
    #print(X)
    mean, cov = mean_cov(X)
    print(mean)
    print(np.cov(X.T))
    print(cov)
    print(cov.T)
    

[[12.04341828 29.92870885 10.00515808]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]


In [477]:
import numpy as np
np.random.seed(1)
N = 10
b1 = np.random.rand(N)
b2 = np.random.rand(N)
#X = np.column_stack([b1, b2])
print(X)
X -= X.mean(axis=0) 
fact = N - 1 
by_hand = np.dot(X.T, X.conj()) / fact
print(by_hand)
# [[ 0.04735338  0.01242557]
#  [ 0.01242557  0.07669083]]

using_cov = np.cov(b1, b2)

assert np.allclose(by_hand, using_cov)

[[ 1.13919349 46.10661566  7.0519495 ]
 [-2.01292265 47.35760007 -4.43391461]
 [ 8.96563372 39.59382658  7.51106974]
 ...
 [ 9.05272289 39.85932266  4.47272097]
 [12.39216481 36.88233254  7.6748657 ]
 [11.56731535 12.90689551 15.23323165]]
[[ 40219.02114274 -33101.1922013   17087.09824345]
 [-33101.1922013  108630.58725544 -22975.14819282]
 [ 17087.09824345 -22975.14819282  27707.8603018 ]]


ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 