In [2]:
#!touch 0-mean_cov.py

In [3]:
!chmod +x *.py

In [497]:
#!/usr/bin/env python3
""" mean cov """
import numpy as np


def mean_cov(X):
    """
    calculate the mean and
    covariance of a data set
    """
    mean = X.mean(axis=0, keepdims=True)
    n = X.shape[0] - 1
    x = X - mean
    cov = np.dot(x.T, X.conj()) / n
    return mean, cov

In [498]:
#!/usr/bin/env python3

if __name__ == '__main__':
    import numpy as np
    #mean_cov = __import__('0-mean_cov').mean_cov

    np.random.seed(0)
    X = np.random.multivariate_normal([12, 30, 10], [[36, -30, 15], [-30, 100, -20], [15, -20, 25]], 10000)
    #print(X)
    mean, cov = mean_cov(X)
    print(mean)
    print(np.cov(X.T))
    print(cov)
    print(cov.T)
    

[[12.04341828 29.92870885 10.00515808]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]


In [536]:
def correlation(C):
    """
    calculate a correlation matrix
    """
    _, cov = mean_cov(C)
    print(cov)
    return cov/(C.std())

In [537]:
#!/usr/bin/env python3

if __name__ == '__main__':
    import numpy as np
    #correlation = __import__('1-correlation').correlation

    C = np.array([[36, -30, 15], [-30, 100, -20], [15, -20, 25]])
    Co = correlation(C)
    print(C)
    print(Co)

[[ 1137.         -2365.           687.5       ]
 [-2365.          5233.33333333 -1641.66666667]
 [  687.5        -1641.66666667   558.33333333]]
[[ 36 -30  15]
 [-30 100 -20]
 [ 15 -20  25]]
[[ 28.7759599  -59.85500895  17.3997119 ]
 [-59.85500895 132.44871606 -41.54840297]
 [ 17.3997119  -41.54840297  14.13067512]]
