In [2]:
!cp 0-mean_cov.py 

In [3]:
!chmod +x *.py

In [497]:
#!/usr/bin/env python3
""" mean cov """
import numpy as np


def mean_cov(X):
    """
    calculate the mean and
    covariance of a data set
    """
    mean = X.mean(axis=0, keepdims=True)
    n = X.shape[0] - 1
    x = X - mean
    cov = np.dot(x.T, X.conj()) / n
    return mean, cov

In [498]:
#!/usr/bin/env python3

if __name__ == '__main__':
    import numpy as np
    #mean_cov = __import__('0-mean_cov').mean_cov

    np.random.seed(0)
    X = np.random.multivariate_normal([12, 30, 10], [[36, -30, 15], [-30, 100, -20], [15, -20, 25]], 10000)
    #print(X)
    mean, cov = mean_cov(X)
    print(mean)
    print(np.cov(X.T))
    print(cov)
    print(cov.T)
    

[[12.04341828 29.92870885 10.00515808]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]
[[ 36.2007391  -29.79405239  15.37992641]
 [-29.79405239  97.77730626 -20.67970134]
 [ 15.37992641 -20.67970134  24.93956823]]


In [576]:
def correlation(C):
    """
    calculate a correlation matrix
    """
    if type(C) is not np.ndarray:
        raise TypeError("C must be a numpy.ndarray")
    if C.shape[0] != C.shape[0]:
        raise ValueError("C must be a 2D square")
    _, cov = mean_cov(C)
    return (np.corrcoef(C))

In [577]:
#!/usr/bin/env python3

if __name__ == '__main__':
    import numpy as np
    #correlation = __import__('1-correlation').correlation

    C = np.array([[36, -30, 15], [-30, 100, -20], [15, -20, 25]])
    Co = correlation(C)
    print(C)
    print(Co)

[[ 36 -30  15]
 [-30 100 -20]
 [ 15 -20  25]]
[[ 1.         -0.96953103  0.86287064]
 [-0.96953103  1.         -0.96039304]
 [ 0.86287064 -0.96039304  1.        ]]
