In [4]:
!chmod +x *.py

In [132]:
!pwd

/home/khouloud/hb/holbertonschool-machine_learning/unsupervised_learning/0x00-dimensionality_reduction


In [208]:
def pca(X):
    # Data matrix X, assumes 0-centered
    n, m = X.shape
    assert np.allclose(X.mean(axis=0), np.zeros(m))
    # Compute covariance matrix
    C = np.dot(X.T, X) / (n-1)
    # Eigen decomposition
    eigen_vals, eigen_vecs = np.linalg.eig(C)
    # Project X onto PC space
    X_pca = np.dot(X, eigen_vecs)
    return eigen_vecs

In [130]:
#!/usr/bin/env python3
""" PCA """
import numpy as np


def pca(X, var=0.95):
    """ performs PCA on a dataset """
    u, s, vh = np.linalg.svd(X)
    n = 0
    s_var = s.sum() * var
    tot = s[0]
    while(tot < s_var):
        n += 1
        tot += s[n]
    return vh[:n+1].T

In [131]:
#!/usr/bin/env python3
from sklearn import decomposition as dec
import numpy as np
#pca = __import__('0-pca').pca

np.random.seed(0)
a = np.random.normal(size=50)
b = np.random.normal(size=50)
c = np.random.normal(size=50)
d = 2 * a
e = -5 * b
f = 10 * c
X = np.array([a, b, c, d, e, f]).T
m = X.shape[0]
X_m = X - np.mean(X, axis=0)
W = pca(X_m)
#W = dec.PCA(X_m)

#print(W)
T = np.dot(X_m, W)

X_t = np.dot(T, W.T)
print(np.sum(np.square(X_m - X_t)) / m)
print(T)

2.306623725743524e-29
[[-16.71379391   3.25277063  -3.21956297]
 [ 16.22654311  -0.7283969   -0.88325252]
 [ 15.05945199   3.81948929  -1.97153621]
 [ -7.69814111   5.49561088  -4.34581561]
 [ 14.25075197   1.37060228  -4.04817187]
 [-16.66888233  -3.77067823   2.6264981 ]
 [  6.71765183   0.18115089  -1.91719288]
 [ 10.20004065  -0.84380128   0.44754302]
 [-16.93427229   1.72241573   0.9006236 ]
 [-12.4100987    0.75431367  -0.36518129]
 [-16.40464248   1.98431953   0.34907508]
 [ -6.69439671   1.30624703  -2.77438892]
 [ 10.84363895   4.99826372  -1.36502623]
 [-17.2656016    7.29822621   0.63226953]
 [  5.32413372  -0.54822516  -0.79075935]
 [ -5.63240657   1.50278876  -0.27590797]
 [ -7.63440366   7.72788006  -2.58344477]
 [  4.3348786   -2.14969035   0.61262033]
 [ -3.95417052   4.22254889  -0.14601319]
 [ -6.59947069  -1.00867621   2.29551761]
 [ -0.78942283  -4.15454151   5.87117533]
 [ 13.62292856   0.40038586  -1.36043631]
 [  0.03536684  -5.85950737  -1.86196569]
 [-11.184129

In [58]:
from sklearn.decomposition import PCA as IncrementalPCA
ipca = IncrementalPCA()
ipca.fit(X_m)
#IncrementalPCA(batch_size=3, n_components=2)
T = ipca.transform(X_m)
print(T)
#T = np.dot(X_m, W)
#print(T)
X_t = T#np.dot(T, W.T)
print(np.sum(np.square(X_m - X_t)) / m)

[[ 1.67137939e+01 -3.25277063e+00 -3.21956297e+00  1.33226763e-15
  -3.60822483e-16  1.66533454e-16]
 [-1.62265431e+01  7.28396898e-01 -8.83252518e-01 -1.11022302e-15
  -3.19189120e-16  7.49400542e-16]
 [-1.50594520e+01 -3.81948929e+00 -1.97153621e+00 -8.88178420e-16
  -1.67921232e-15  5.82867088e-16]
 [ 7.69814111e+00 -5.49561088e+00 -4.34581561e+00  6.66133815e-16
  -1.40859546e-15  3.95516953e-16]
 [-1.42507520e+01 -1.37060228e+00 -4.04817187e+00 -1.11022302e-15
  -7.91033905e-16  1.23512311e-15]
 [ 1.66688823e+01  3.77067823e+00  2.62649810e+00  1.33226763e-15
   1.49880108e-15 -7.49400542e-16]
 [-6.71765183e+00 -1.81150892e-01 -1.91719288e+00 -6.66133815e-16
  -2.22044605e-16  6.24500451e-16]
 [-1.02000406e+01  8.43801282e-01  4.47543019e-01 -6.66133815e-16
  -5.55111512e-17  2.08166817e-16]
 [ 1.69342723e+01 -1.72241573e+00  9.00623596e-01  1.11022302e-15
  -2.77555756e-17 -8.04911693e-16]
 [ 1.24100987e+01 -7.54313670e-01 -3.65181287e-01  1.11022302e-15
   1.11022302e-16 -2.7755

In [136]:
#!/usr/bin/env python3
""" PCA """
import numpy as np


def pca(X, ndim):
    """ performs PCA on a dataset """
    u, s, vh = np.linalg.svd(X)

    return vh[:ndim].T

In [137]:
#!/usr/bin/env python3

import numpy as np
#pca = __import__('1-pca').pca

X = np.loadtxt("mnist2500_X.txt")
print('X:', X.shape)
print(X)
T = pca(X, 50)
print('T:', T.shape)
print(T)

X: (2500, 784)
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
T: (50, 784)
[[-0.04230034 -0.04230034 -0.04230034 ... -0.04230034 -0.04230034
  -0.04230034]
 [-0.01520813 -0.01520813 -0.01520813 ... -0.01520813 -0.01520813
  -0.01520813]
 [ 0.00258955  0.00258955  0.00258955 ...  0.00258955  0.00258955
   0.00258955]
 ...
 [ 0.00105702  0.00105702  0.00105702 ...  0.00105702  0.00105702
   0.00105702]
 [-0.00188842 -0.00188842 -0.00188842 ... -0.00188842 -0.00188842
  -0.00188842]
 [-0.00074905 -0.00074905 -0.00074905 ... -0.00074905 -0.00074905
  -0.00074905]]


In [233]:
4.51029348e+06 + 3.85413405e-10 + 1.15315322e+04 + 1.59281241e+05-2.40535305e-11 + 1.12352636e-10

4681106.253200001

In [262]:
#!/usr/bin/env python
""" a small class for Principal Component Analysis
Usage:
    p = PCA( A, fraction=0.90 )
In:
    A: an array of e.g. 1000 observations x 20 variables, 1000 rows x 20 columns
    fraction: use principal components that account for e.g.
        90 % of the total variance

Out:
    p.U, p.d, p.Vt: from numpy.linalg.svd, A = U . d . Vt
    p.dinv: 1/d or 0, see NR
    p.eigen: the eigenvalues of A*A, in decreasing order (p.d**2).
        eigen[j] / eigen.sum() is variable j's fraction of the total variance;
        look at the first few eigen[] to see how many PCs get to 90 %, 95 % ...
    p.npc: number of principal components,
        e.g. 2 if the top 2 eigenvalues are >= `fraction` of the total.
        It's ok to change this; methods use the current value.

Methods:
    The methods of class PCA transform vectors or arrays of e.g.
    20 variables, 2 principal components and 1000 observations,
    using partial matrices U' d' Vt', parts of the full U d Vt:
    A ~ U' . d' . Vt' where e.g.
        U' is 1000 x 2
        d' is diag([ d0, d1 ]), the 2 largest singular values
        Vt' is 2 x 20.  Dropping the primes,

    d . Vt      2 principal vars = p.vars_pc( 20 vars )
    U           1000 obs = p.pc_obs( 2 principal vars )
    U . d . Vt  1000 obs, p.obs( 20 vars ) = pc_obs( vars_pc( vars ))
        fast approximate A . vars, using the `npc` principal components

    Ut              2 pcs = p.obs_pc( 1000 obs )
    V . dinv        20 vars = p.pc_vars( 2 principal vars )
    V . dinv . Ut   20 vars, p.vars( 1000 obs ) = pc_vars( obs_pc( obs )),
        fast approximate Ainverse . obs: vars that give ~ those obs.


Notes:
    PCA does not center or scale A; you usually want to first
        A -= A.mean(A, axis=0)
        A /= A.std(A, axis=0)
    with the little class Center or the like, below.

See also:
    http://en.wikipedia.org/wiki/Principal_component_analysis
    http://en.wikipedia.org/wiki/Singular_value_decomposition
    Press et al., Numerical Recipes (2 or 3 ed), SVD
    PCA micro-tutorial
    iris-pca .py .png

"""

from __future__ import division
import numpy as np
dot = np.dot
    # import bz.numpyutil as nu
    # dot = nu.pdot

__version__ = "2010-04-14 apr"
__author_email__ = "denis-bz-py at t-online dot de"

#...............................................................................
class PCA:
    def __init__( self, A, fraction=0.90 ):
        assert 0 <= fraction <= 1
            # A = U . diag(d) . Vt, O( m n^2 ), lapack_lite --
        self.U, self.d, self.Vt = np.linalg.svd( A, full_matrices=False )
        assert np.all( self.d[:-1] >= self.d[1:] )  # sorted
        self.eigen = self.d**2
        self.sumvariance = np.cumsum(self.eigen)
        self.sumvariance /= self.sumvariance[-1]
        self.npc = np.searchsorted( self.sumvariance, fraction ) + 1
        self.dinv = np.array([ 1/d if d > self.d[0] * 1e-6  else 0
                                for d in self.d ])

    def pc( self ):
        """ e.g. 1000 x 2 U[:, :npc] * d[:npc], to plot etc. """
        n = self.npc
        return self.U[:, :n] * self.d[:n]

    # These 1-line methods may not be worth the bother;
    # then use U d Vt directly --

    def vars_pc( self, x ):
        n = self.npc
        return self.d[:n] * dot( self.Vt[:n], x.T ).T  # 20 vars -> 2 principal

    def pc_vars( self, p ):
        n = self.npc
        return dot( self.Vt[:n].T, (self.dinv[:n] * p).T ) .T  # 2 PC -> 20 vars

    def pc_obs( self, p ):
        n = self.npc
        return dot( self.U[:, :n], p.T )  # 2 principal -> 1000 obs

    def obs_pc( self, obs ):
        n = self.npc
        return dot( self.U[:, :n].T, obs ) .T  # 1000 obs -> 2 principal

    def obs( self, x ):
        return self.pc_obs( self.vars_pc(x) )  # 20 vars -> 2 principal -> 1000 obs

    def vars( self, obs ):
        return self.pc_vars( self.obs_pc(obs) )  # 1000 obs -> 2 principal -> 20 vars


class Center:
    """ A -= A.mean() /= A.std(), inplace -- use A.copy() if need be
        uncenter(x) == original A . x
    """
        # mttiw
    def __init__( self, A, axis=0, scale=True, verbose=1 ):
        self.mean = A.mean(axis=axis)
        if verbose:
            print ("Center -= A.mean:", self.mean)
        A -= self.mean
        if scale:
            std = A.std(axis=axis)
            self.std = np.where( std, std, 1. )
            if verbose:
                print("Center /= A.std:", self.std)
            A /= self.std
        else:
            self.std = np.ones( A.shape[-1] )
        self.A = A

    def uncenter( self, x ):
        return np.dot( self.A, x * self.std ) + np.dot( x, self.mean )

