In [43]:
#!cp 0-markov_chain.py 1-regular.py
#!chmod +x *.py

In [40]:
import numpy as np

v = np.array([[1, 0]])
v2 = np.array([[1/2, 1/2], [1/3, 2/3]])
np.dot(v, np.linalg.matrix_power(v2, 3))

array([[0.40277778, 0.59722222]])

In [8]:
29/72 , 43/72

(0.4027777777777778, 0.5972222222222222)

In [41]:
def markov_chain(P, s, t=1):
    """
    determines the probability of a markov chain
    being in a particular state after a specified
    number of iterations
    """
    if ((type(P) is not np.ndarray or type(s) is not np.ndarray
         or P.ndim != 2 or s.ndim != 2 or P.shape[0] != P.shape[1]
         or s.shape[0] != 1 or s.shape[1] != P.shape[0]
         or type(t) is not int or t < 0)):
        return None
    return np.matmul(s, np.linalg.matrix_power(P, t))
print(markov_chain(v2, v, 3))

[[0.40277778 0.59722222]]


In [42]:
if __name__ == "__main__":
    P = np.array([[0.25, 0.2, 0.25, 0.3], [0.2, 0.3, 0.2, 0.3], [0.25, 0.25, 0.4, 0.1], [0.3, 0.3, 0.1, 0.3]])
    s = np.array([[1, 0, 0, 0]])
    print(markov_chain(P, s, 300))

[[0.2494929  0.26335362 0.23394185 0.25321163]]


In [66]:
def regular(P):
    """
    determines the steady state probabilities
    of a regular markov chain
    """
    if (type(P) is not np.ndarray or P.ndim != 2
        or P.shape[0] != P.shape[1] or np.any(P <= 0)
        or not np.all(np.isclose(P.sum(axis=1), 1))):
        return None
    try:
        dim = P.shape[0]
        q = (P - np.eye(dim))
        ones = np.ones(dim)
        q = np.c_[q,ones]
        QTQ = np.dot(q, q.T)
        bQT = np.ones(dim)
        return np.expand_dims(np.linalg.solve(QTQ, bQT), 0)
    except Exception:
        return None
#regular()

In [69]:
#!/usr/bin/env python3

import numpy as np
regular = __import__('1-regular').regular

if __name__ == '__main__':
    a = np.eye(2)
    b = np.array([[0.6, 0.4],
                  [0.3, 0.7]])
    c = np.array([[0.25, 0.2, 0.25, 0.3],
                  [0.2, 0.3, 0.2, 0.3],
                  [0.25, 0.25, 0.4, 0.1],
                  [0.3, 0.3, 0.1, 0.3]])
    d = np.array([[0.8, 0.2, 0, 0, 0],
                [0.25, 0.75, 0, 0, 0],
                [0, 0, 0.5, 0.2, 0.3],
                [0, 0, 0.3, 0.5, .2],
                [0, 0, 0.2, 0.3, 0.5]])
    e = np.array([[1, 0.25, 0, 0, 0],
                [0.25, 0.75, 0, 0, 0],
                [0, 0.1, 0.5, 0.2, 0.2],
                [0, 0.1, 0.2, 0.5, .2],
                [0, 0.1, 0.2, 0.2, 0.5]])
    print(regular(a))
    print(regular(b))
    print(regular(c))
    print(regular(d))
    print(regular(e))

None
[[0.42857143 0.57142857]]
[[0.2494929  0.26335362 0.23394185 0.25321163]]
None
None
