In [1]:
!touch 0-markov_chain.py
#!chmod +x *.py

In [40]:
import numpy as np

v = np.array([[1, 0]])
v2 = np.array([[1/2, 1/2], [1/3, 2/3]])
np.dot(v, np.linalg.matrix_power(v2, 3))

array([[0.40277778, 0.59722222]])

In [8]:
29/72 , 43/72

(0.4027777777777778, 0.5972222222222222)

In [41]:
def markov_chain(P, s, t=1):
    """
    determines the probability of a markov chain
    being in a particular state after a specified
    number of iterations
    """
    if ((type(P) is not np.ndarray or type(s) is not np.ndarray
         or P.ndim != 2 or s.ndim != 2 or P.shape[0] != P.shape[1]
         or s.shape[0] != 1 or s.shape[1] != P.shape[0]
         or type(t) is not int or t < 0)):
        return None
    return np.matmul(s, np.linalg.matrix_power(P, t))
print(markov_chain(v2, v, 3))

[[0.40277778 0.59722222]]


In [42]:
if __name__ == "__main__":
    P = np.array([[0.25, 0.2, 0.25, 0.3], [0.2, 0.3, 0.2, 0.3], [0.25, 0.25, 0.4, 0.1], [0.3, 0.3, 0.1, 0.3]])
    s = np.array([[1, 0, 0, 0]])
    print(markov_chain(P, s, 300))

[[0.2494929  0.26335362 0.23394185 0.25321163]]
