In [143]:
#!cp 3-forward.py 5-backward.py
#!chmod +x *.py
#!pwd

In [40]:
import numpy as np

v = np.array([[1, 0]])
v2 = np.array([[1/2, 1/2], [1/3, 2/3]])
np.dot(v, np.linalg.matrix_power(v2, 3))

array([[0.40277778, 0.59722222]])

In [8]:
29/72 , 43/72

(0.4027777777777778, 0.5972222222222222)

In [41]:
def markov_chain(P, s, t=1):
    """
    determines the probability of a markov chain
    being in a particular state after a specified
    number of iterations
    """
    if ((type(P) is not np.ndarray or type(s) is not np.ndarray
         or P.ndim != 2 or s.ndim != 2 or P.shape[0] != P.shape[1]
         or s.shape[0] != 1 or s.shape[1] != P.shape[0]
         or type(t) is not int or t < 0)):
        return None
    return np.matmul(s, np.linalg.matrix_power(P, t))
print(markov_chain(v2, v, 3))

[[0.40277778 0.59722222]]


In [42]:
if __name__ == "__main__":
    P = np.array([[0.25, 0.2, 0.25, 0.3], [0.2, 0.3, 0.2, 0.3], [0.25, 0.25, 0.4, 0.1], [0.3, 0.3, 0.1, 0.3]])
    s = np.array([[1, 0, 0, 0]])
    print(markov_chain(P, s, 300))

[[0.2494929  0.26335362 0.23394185 0.25321163]]


In [66]:
def regular(P):
    """
    determines the steady state probabilities
    of a regular markov chain
    """
    if (type(P) is not np.ndarray or P.ndim != 2
        or P.shape[0] != P.shape[1] or np.any(P <= 0)
        or not np.all(np.isclose(P.sum(axis=1), 1))):
        return None
    try:
        dim = P.shape[0]
        q = (P - np.eye(dim))
        ones = np.ones(dim)
        q = np.c_[q,ones]
        QTQ = np.dot(q, q.T)
        bQT = np.ones(dim)
        return np.expand_dims(np.linalg.solve(QTQ, bQT), 0)
    except Exception:
        return None
#regular()

In [73]:
#!/usr/bin/env python3

import numpy as np
regular = __import__('1-regular').regular

if __name__ == '__main__':
    a = np.eye(2)
    b = np.array([[0.6, 0.4],
                  [0.3, 0.7]])
    c = np.array([[0.25, 0.2, 0.25, 0.3],
                  [0.2, 0.3, 0.2, 0.3],
                  [0.25, 0.25, 0.4, 0.1],
                  [0.3, 0.3, 0.1, 0.3]])
    d = np.array([[0.8, 0.2, 0, 0, 0],
                [0.25, 0.75, 0, 0, 0],
                [0, 0, 0.5, 0.2, 0.3],
                [0, 0, 0.3, 0.5, .2],
                [0, 0, 0.2, 0.3, 0.5]])
    e = np.array([[1, 0.25, 0, 0, 0],
                [0.25, 0.75, 0, 0, 0],
                [0, 0.1, 0.5, 0.2, 0.2],
                [0, 0.1, 0.2, 0.5, .2],
                [0, 0.1, 0.2, 0.2, 0.5]])
    print(regular(a))
    print(regular(b))
    print(regular(c))
    print(regular(d))
    print(regular(e))

None
[[0.42857143 0.57142857]]
[[0.2494929  0.26335362 0.23394185 0.25321163]]
None
None


In [5]:
import numpy as np

def absorbing(P):
    if type(P) is not np.ndarray or P.ndim != 2\
       or P.shape[0] != P.shape[1] or np.any(P < 0)\
       or not np.all(np.isclose(P.sum(axis=1), 1)):
        return False

    for i in range(P.shape[0]):
        if P[i, i] == 1:
            return True
    return False
if __name__ == '__main__':
    a = np.eye(2)
    b = np.array([[0.6, 0.4],
                  [0.3, 0.7]])
    c = np.array([[0.25, 0.2, 0.25, 0.3],
                  [0.2, 0.3, 0.2, 0.3],
                  [0.25, 0.25, 0.4, 0.1],
                  [0.3, 0.3, 0.1, 0.3]])
    d = np.array([[1, 0, 0, 0, 0],
                  [0.25, 0.75, 0, 0, 0],
                  [0, 0, 0.5, 0.2, 0.3],
                  [0, 0, 0.3, 0.5, .2],
                  [0, 0, 0.2, 0.3, 0.5]])
    e = np.array([[1, 0, 0, 0, 0],
                  [0.25, 0.75, 0, 0, 0],
                  [0, 0.1, 0.5, 0.2, 0.2],
                  [0, 0.1, 0.2, 0.5, .2],
                  [0, 0.1, 0.2, 0.2, 0.5]])
    f = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 0.5, 0.5],
                  [0, 0.5, 0.5, 0]])
    print(absorbing(a))
    print(absorbing(b))
    print(absorbing(c))
    print(absorbing(d))
    print(absorbing(e))
    print(absorbing(f))

True
False
False
True
True
True


In [127]:
import numpy as np

V = np.array([0, 1, 1, 2, 0, 1, 2, 0, 1, 0, 2]) 

# Transition Probabilities
a = np.array(((0.54, 0.46), (0.49, 0.51)))

# Emission Probabilities
b = np.array(((0.16, 0.26, 0.58), (0.25, 0.28, 0.47)))

# # Equal Probabilities for the initial distribution
pi = np.array((0.5, 0.5))

def forward(V, a, b, pi):
    p = 1
    alpha = np.zeros((V.shape[0], a.shape[0]))
    alpha[0, :] = pi * b[0, V[0]]

    for t in range(1, V.shape[0]):
        probability_of_observation = 0 #my code
        for j in range(a.shape[0]):
            alpha[t, j] = alpha[t - 1].dot(a[:, j]) * b[j, V[t]]
            probability_of_observation += alpha[t, j]  #my code
        p = p * probability_of_observation #my code

    return p, alpha #changed

p, alpha = forward(V, a, b, pi)  #changed
print(p)
print(alpha)

1.645863905329049e-37
[[8.00000000e-02 8.00000000e-02]
 [2.14240000e-02 2.17280000e-02]
 [5.77607680e-03 5.86216960e-03]
 [3.47509585e-03 2.65394986e-03]
 [5.08317951e-04 7.38014630e-04]
 [1.65390904e-04 1.70859841e-04]
 [1.00358798e-04 7.67126174e-05]
 [1.46852694e-05 2.13221205e-05]
 [4.77824997e-06 4.93626150e-06]
 [7.99843699e-07 1.17887209e-06]
 [5.85546494e-07 4.55501847e-07]]


In [140]:
def forward(Obs, Emiss, Trans, Init):
    T = Obs.shape[0]
    N, M = Emiss.shape
    alpha = np.zeros((N, T))

    for t in range(T):
        for s in range(N):
            if t == 0:
                alpha[s, 0] = Init[s, 0] * Emiss[s, Obs[t]]
            else:
                alpha[s, t] = np.sum(alpha[:, t - 1]
                                     * Trans[:, s]
                                     * Emiss[s, Obs[t]])

    return np.sum(alpha[:, T-1]), alpha 


np.random.seed(1)
Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                     [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                     [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                     [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                     [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                       [0.20, 0.50, 0.30, 0.00, 0.00],
                       [0.01, 0.24, 0.50, 0.24, 0.01],
                       [0.00, 0.00, 0.15, 0.70, 0.15],
                       [0.00, 0.00, 0.01, 0.39, 0.60]])
Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
Hidden = [np.random.choice(5, p=Initial)]
for _ in range(364):
    Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
Hidden = np.array(Hidden)
Observations = []
for s in Hidden:
    Observations.append(np.random.choice(6, p=Emission[s]))
Observations = np.array(Observations)
P, F = forward(Observations, Emission, Transition, Initial.reshape((-1, 1)))
print(P)
print(F)

1.7080966131859584e-214
[[0.00000000e+000 0.00000000e+000 2.98125000e-004 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [2.00000000e-002 0.00000000e+000 3.18000000e-003 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [2.50000000e-001 3.31250000e-002 0.00000000e+000 ... 2.13885975e-214
  1.17844112e-214 0.00000000e+000]
 [1.00000000e-002 4.69000000e-002 0.00000000e+000 ... 2.41642482e-213
  1.27375484e-213 9.57568349e-215]
 [0.00000000e+000 8.00000000e-004 0.00000000e+000 ... 1.96973759e-214
  9.65573676e-215 7.50528264e-215]]


In [141]:
#!/usr/bin/env python3

import numpy as np
def viterbi(Obs, Emiss, Trans, Init):
    """
    performs the forward algorithm
    for a hidden markov model
    """
    T = Obs.shape[0]
    N, M = Emiss.shape
    V = np.zeros((N, T))
    B = np.zeros((N, T))

    for t in range(T):
        for s in range(N):
            if t == 0:
                V[s, 0] = Init[s, 0] * Emiss[s, Obs[t]]
            else:
                tmp = V[:, t - 1] * Trans[:, s] * Emiss[s, Obs[t]]
                V[s, t] = np.max(tmp)
                B[s, t] = np.argmax(tmp)
    P = np.max(V[:, T-1])
    pointer = np.argmax(V[:, T-1])
    path = [pointer]
    for t in range(T-1, 0, -1):
        pr = int(B[pointer, t])
        path.append(pr)
        pointer = pr

    return path[::-1], P



if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                         [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                         [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                         [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                         [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
    Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                           [0.20, 0.50, 0.30, 0.00, 0.00],
                           [0.01, 0.24, 0.50, 0.24, 0.01],
                           [0.00, 0.00, 0.15, 0.70, 0.15],
                           [0.00, 0.00, 0.01, 0.39, 0.60]])
    Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
    Hidden = [np.random.choice(5, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(6, p=Emission[s]))
    Observations = np.array(Observations)
    path, P = viterbi(Observations, Emission, Transition, Initial.reshape((-1, 1)))
    print(P)
    print(path)

4.701733355108224e-252
[2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 2, 2, 2, 3, 3, 3, 2, 1, 2, 1, 1, 2, 2, 2, 3, 3, 2, 2, 3, 4, 4, 3, 3, 2, 2, 3, 3, 3, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 3, 3, 2, 1, 2, 1, 1, 1, 2, 2, 3, 4, 4, 4, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 3, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 1, 0, 0, 0, 1, 2, 2, 1, 1, 2, 3, 3, 2, 1, 1, 1, 2, 3, 3, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 3, 3, 3, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 4, 4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0, 0, 0

In [190]:
def backward(Obs, Emiss, Trans, Init):
    """
    performs the backward algorithm
    for a hidden markov model
    """
    T = Obs.shape[0]
    N, M = Emiss.shape
    alpha = np.zeros((N, T))
    state = np.asarray([1] * N)
    alpha[:, -1] = state
    for t in range(T - 2, -1, -1):
        state = np.matmul(Trans, state * Emiss[:, Obs[t + 1]])
        alpha[:, t] = state
    return (alpha[:, 0] * Init[:, 0]
            * Emiss[:, Obs[0]]).sum(), alpha

if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                         [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                         [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                         [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                         [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
    Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                           [0.20, 0.50, 0.30, 0.00, 0.00],
                           [0.01, 0.24, 0.50, 0.24, 0.01],
                           [0.00, 0.00, 0.15, 0.70, 0.15],
                           [0.00, 0.00, 0.01, 0.39, 0.60]])
    Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
    Hidden = [np.random.choice(5, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(6, p=Emission[s]))
    Observations = np.array(Observations)
    P, B = backward(Observations, Emission, Transition, Initial.reshape((-1, 1)))
    print(P)
    print(B)

1.7080966131859594e-214
[[1.28912952e-215 6.12087935e-212 1.00555701e-211 ... 6.75000000e-005
  0.00000000e+000 1.00000000e+000]
 [3.86738856e-214 2.69573528e-212 4.42866330e-212 ... 2.02500000e-003
  0.00000000e+000 1.00000000e+000]
 [6.44564760e-214 5.15651808e-213 8.47145100e-213 ... 2.31330000e-002
  2.70000000e-002 1.00000000e+000]
 [1.93369428e-214 0.00000000e+000 0.00000000e+000 ... 6.39325000e-002
  1.15000000e-001 1.00000000e+000]
 [1.28912952e-215 0.00000000e+000 0.00000000e+000 ... 5.77425000e-002
  2.19000000e-001 1.00000000e+000]]
