In [6]:
#!cp 3-forward.py 6-baum_welch.py
#!chmod +x *.py
!pwd
#Markov@chain1999

/home/khouloud/hb/holbertonschool-machine_learning/unsupervised_learning/0x02-hmm


In [40]:
import numpy as np

v = np.array([[1, 0]])
v2 = np.array([[1/2, 1/2], [1/3, 2/3]])
np.dot(v, np.linalg.matrix_power(v2, 3))

array([[0.40277778, 0.59722222]])

In [8]:
29/72 , 43/72

(0.4027777777777778, 0.5972222222222222)

In [41]:
def markov_chain(P, s, t=1):
    """
    determines the probability of a markov chain
    being in a particular state after a specified
    number of iterations
    """
    if ((type(P) is not np.ndarray or type(s) is not np.ndarray
         or P.ndim != 2 or s.ndim != 2 or P.shape[0] != P.shape[1]
         or s.shape[0] != 1 or s.shape[1] != P.shape[0]
         or type(t) is not int or t < 0)):
        return None
    return np.matmul(s, np.linalg.matrix_power(P, t))
print(markov_chain(v2, v, 3))

[[0.40277778 0.59722222]]


In [42]:
if __name__ == "__main__":
    P = np.array([[0.25, 0.2, 0.25, 0.3], [0.2, 0.3, 0.2, 0.3], [0.25, 0.25, 0.4, 0.1], [0.3, 0.3, 0.1, 0.3]])
    s = np.array([[1, 0, 0, 0]])
    print(markov_chain(P, s, 300))

[[0.2494929  0.26335362 0.23394185 0.25321163]]


In [66]:
def regular(P):
    """
    determines the steady state probabilities
    of a regular markov chain
    """
    if (type(P) is not np.ndarray or P.ndim != 2
        or P.shape[0] != P.shape[1] or np.any(P <= 0)
        or not np.all(np.isclose(P.sum(axis=1), 1))):
        return None
    try:
        dim = P.shape[0]
        q = (P - np.eye(dim))
        ones = np.ones(dim)
        q = np.c_[q,ones]
        QTQ = np.dot(q, q.T)
        bQT = np.ones(dim)
        return np.expand_dims(np.linalg.solve(QTQ, bQT), 0)
    except Exception:
        return None
#regular()

In [73]:
#!/usr/bin/env python3

import numpy as np
regular = __import__('1-regular').regular

if __name__ == '__main__':
    a = np.eye(2)
    b = np.array([[0.6, 0.4],
                  [0.3, 0.7]])
    c = np.array([[0.25, 0.2, 0.25, 0.3],
                  [0.2, 0.3, 0.2, 0.3],
                  [0.25, 0.25, 0.4, 0.1],
                  [0.3, 0.3, 0.1, 0.3]])
    d = np.array([[0.8, 0.2, 0, 0, 0],
                [0.25, 0.75, 0, 0, 0],
                [0, 0, 0.5, 0.2, 0.3],
                [0, 0, 0.3, 0.5, .2],
                [0, 0, 0.2, 0.3, 0.5]])
    e = np.array([[1, 0.25, 0, 0, 0],
                [0.25, 0.75, 0, 0, 0],
                [0, 0.1, 0.5, 0.2, 0.2],
                [0, 0.1, 0.2, 0.5, .2],
                [0, 0.1, 0.2, 0.2, 0.5]])
    print(regular(a))
    print(regular(b))
    print(regular(c))
    print(regular(d))
    print(regular(e))

None
[[0.42857143 0.57142857]]
[[0.2494929  0.26335362 0.23394185 0.25321163]]
None
None


In [5]:
import numpy as np

def absorbing(P):
    if type(P) is not np.ndarray or P.ndim != 2\
       or P.shape[0] != P.shape[1] or np.any(P < 0)\
       or not np.all(np.isclose(P.sum(axis=1), 1)):
        return False

    for i in range(P.shape[0]):
        if P[i, i] == 1:
            return True
    return False
if __name__ == '__main__':
    a = np.eye(2)
    b = np.array([[0.6, 0.4],
                  [0.3, 0.7]])
    c = np.array([[0.25, 0.2, 0.25, 0.3],
                  [0.2, 0.3, 0.2, 0.3],
                  [0.25, 0.25, 0.4, 0.1],
                  [0.3, 0.3, 0.1, 0.3]])
    d = np.array([[1, 0, 0, 0, 0],
                  [0.25, 0.75, 0, 0, 0],
                  [0, 0, 0.5, 0.2, 0.3],
                  [0, 0, 0.3, 0.5, .2],
                  [0, 0, 0.2, 0.3, 0.5]])
    e = np.array([[1, 0, 0, 0, 0],
                  [0.25, 0.75, 0, 0, 0],
                  [0, 0.1, 0.5, 0.2, 0.2],
                  [0, 0.1, 0.2, 0.5, .2],
                  [0, 0.1, 0.2, 0.2, 0.5]])
    f = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 0.5, 0.5],
                  [0, 0.5, 0.5, 0]])
    print(absorbing(a))
    print(absorbing(b))
    print(absorbing(c))
    print(absorbing(d))
    print(absorbing(e))
    print(absorbing(f))

True
False
False
True
True
True


In [127]:
import numpy as np

V = np.array([0, 1, 1, 2, 0, 1, 2, 0, 1, 0, 2]) 

# Transition Probabilities
a = np.array(((0.54, 0.46), (0.49, 0.51)))

# Emission Probabilities
b = np.array(((0.16, 0.26, 0.58), (0.25, 0.28, 0.47)))

# # Equal Probabilities for the initial distribution
pi = np.array((0.5, 0.5))

def forward(V, a, b, pi):
    p = 1
    alpha = np.zeros((V.shape[0], a.shape[0]))
    alpha[0, :] = pi * b[0, V[0]]

    for t in range(1, V.shape[0]):
        probability_of_observation = 0 #my code
        for j in range(a.shape[0]):
            alpha[t, j] = alpha[t - 1].dot(a[:, j]) * b[j, V[t]]
            probability_of_observation += alpha[t, j]  #my code
        p = p * probability_of_observation #my code

    return p, alpha #changed

p, alpha = forward(V, a, b, pi)  #changed
print(p)
print(alpha)

1.645863905329049e-37
[[8.00000000e-02 8.00000000e-02]
 [2.14240000e-02 2.17280000e-02]
 [5.77607680e-03 5.86216960e-03]
 [3.47509585e-03 2.65394986e-03]
 [5.08317951e-04 7.38014630e-04]
 [1.65390904e-04 1.70859841e-04]
 [1.00358798e-04 7.67126174e-05]
 [1.46852694e-05 2.13221205e-05]
 [4.77824997e-06 4.93626150e-06]
 [7.99843699e-07 1.17887209e-06]
 [5.85546494e-07 4.55501847e-07]]


In [2]:
def forward(Obs, Emiss, Trans, Init):
    T = Obs.shape[0]
    N, M = Emiss.shape
    alpha = np.zeros((N, T))

    for t in range(T):
        for s in range(N):
            if t == 0:
                alpha[s, 0] = Init[s, 0] * Emiss[s, Obs[t]]
            else:
                alpha[s, t] = np.sum(alpha[:, t - 1]
                                     * Trans[:, s]
                                     * Emiss[s, Obs[t]])

    return np.sum(alpha[:, T-1]), alpha 


np.random.seed(1)
Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                     [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                     [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                     [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                     [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                       [0.20, 0.50, 0.30, 0.00, 0.00],
                       [0.01, 0.24, 0.50, 0.24, 0.01],
                       [0.00, 0.00, 0.15, 0.70, 0.15],
                       [0.00, 0.00, 0.01, 0.39, 0.60]])
Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
Hidden = [np.random.choice(5, p=Initial)]
for _ in range(364):
    Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
Hidden = np.array(Hidden)
Observations = []
for s in Hidden:
    Observations.append(np.random.choice(6, p=Emission[s]))
Observations = np.array(Observations)
P, F = forward(Observations, Emission, Transition, Initial.reshape((-1, 1)))
print(P)
print(F)

1.7080966131859584e-214
[[0.00000000e+000 0.00000000e+000 2.98125000e-004 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [2.00000000e-002 0.00000000e+000 3.18000000e-003 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [2.50000000e-001 3.31250000e-002 0.00000000e+000 ... 2.13885975e-214
  1.17844112e-214 0.00000000e+000]
 [1.00000000e-002 4.69000000e-002 0.00000000e+000 ... 2.41642482e-213
  1.27375484e-213 9.57568349e-215]
 [0.00000000e+000 8.00000000e-004 0.00000000e+000 ... 1.96973759e-214
  9.65573676e-215 7.50528264e-215]]


In [141]:
#!/usr/bin/env python3

import numpy as np
def viterbi(Obs, Emiss, Trans, Init):
    """
    performs the forward algorithm
    for a hidden markov model
    """
    T = Obs.shape[0]
    N, M = Emiss.shape
    V = np.zeros((N, T))
    B = np.zeros((N, T))

    for t in range(T):
        for s in range(N):
            if t == 0:
                V[s, 0] = Init[s, 0] * Emiss[s, Obs[t]]
            else:
                tmp = V[:, t - 1] * Trans[:, s] * Emiss[s, Obs[t]]
                V[s, t] = np.max(tmp)
                B[s, t] = np.argmax(tmp)
    P = np.max(V[:, T-1])
    pointer = np.argmax(V[:, T-1])
    path = [pointer]
    for t in range(T-1, 0, -1):
        pr = int(B[pointer, t])
        path.append(pr)
        pointer = pr

    return path[::-1], P



if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                         [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                         [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                         [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                         [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
    Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                           [0.20, 0.50, 0.30, 0.00, 0.00],
                           [0.01, 0.24, 0.50, 0.24, 0.01],
                           [0.00, 0.00, 0.15, 0.70, 0.15],
                           [0.00, 0.00, 0.01, 0.39, 0.60]])
    Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
    Hidden = [np.random.choice(5, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(6, p=Emission[s]))
    Observations = np.array(Observations)
    path, P = viterbi(Observations, Emission, Transition, Initial.reshape((-1, 1)))
    print(P)
    print(path)

4.701733355108224e-252
[2, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 2, 2, 2, 3, 3, 3, 2, 1, 2, 1, 1, 2, 2, 2, 3, 3, 2, 2, 3, 4, 4, 3, 3, 2, 2, 3, 3, 3, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 3, 3, 2, 1, 2, 1, 1, 1, 2, 2, 3, 4, 4, 4, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 3, 2, 2, 3, 2, 2, 3, 4, 4, 4, 3, 2, 1, 0, 0, 0, 1, 2, 2, 1, 1, 2, 3, 3, 2, 1, 1, 1, 2, 3, 3, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 3, 3, 4, 4, 4, 4, 3, 3, 3, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 4, 4, 4, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 1, 2, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 0, 0, 0

In [191]:
def backward(Obs, Emiss, Trans, Init):
    """
    performs the backward algorithm
    for a hidden markov model
    """
    T = Obs.shape[0]
    N, M = Emiss.shape
    alpha = np.zeros((N, T))
    state = np.ones([1] * N)
    alpha[:, -1] = state
    for t in range(T - 2, -1, -1):
        state = np.matmul(Trans, state * Emiss[:, Obs[t + 1]])
        alpha[:, t] = state
    return (alpha[:, 0] * Init[:, 0]
            * Emiss[:, Obs[0]]).sum(), alpha

if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                         [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                         [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                         [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                         [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
    Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                           [0.20, 0.50, 0.30, 0.00, 0.00],
                           [0.01, 0.24, 0.50, 0.24, 0.01],
                           [0.00, 0.00, 0.15, 0.70, 0.15],
                           [0.00, 0.00, 0.01, 0.39, 0.60]])
    Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
    Hidden = [np.random.choice(5, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(6, p=Emission[s]))
    Observations = np.array(Observations)
    P, B = backward(Observations, Emission, Transition, Initial.reshape((-1, 1)))
    print(P)
    print(B)

1.7080966131859594e-214
[[1.28912952e-215 6.12087935e-212 1.00555701e-211 ... 6.75000000e-005
  0.00000000e+000 1.00000000e+000]
 [3.86738856e-214 2.69573528e-212 4.42866330e-212 ... 2.02500000e-003
  0.00000000e+000 1.00000000e+000]
 [6.44564760e-214 5.15651808e-213 8.47145100e-213 ... 2.31330000e-002
  2.70000000e-002 1.00000000e+000]
 [1.93369428e-214 0.00000000e+000 0.00000000e+000 ... 6.39325000e-002
  1.15000000e-001 1.00000000e+000]
 [1.28912952e-215 0.00000000e+000 0.00000000e+000 ... 5.77425000e-002
  2.19000000e-001 1.00000000e+000]]


In [61]:
#!/usr/bin/env python3

import numpy as np

def baum_welch(Obs, Trans, Emiss, Init, iterations=1000):
    """
    performs the Baum-Welch algorithm for a hidden markov model
    """
    T = Obs.shape[0]
    N, M = Emiss.shape

    def forward(Obs, Trans, Emiss, Init):
        """ baum welch forward """
        alpha = np.ndarray((N, T))
        state = Init[:, 0]
        for t in range(T):
            state = state * Emiss[:, Obs[t]]
            alpha[:, t] = state
            state = np.matmul(Trans.T, state)
        return alpha[:, -1].sum(), alpha

    def backward(Obs, Trans, Emiss, Init):
        """ baum welch backward """
        beta = np.ndarray((N, T))
        state = np.asarray([1] * N)
        beta[:, -1] = state
        for t in range(T - 2, -1, -1):
            state = np.matmul(Trans, state * Emiss[:, Obs[t + 1]])
            beta[:, t] = state
        return (beta[:, 0] * Init[:, 0]
                * Emiss[:, Obs[0]]).sum(), beta
    transprev = None
    initprev = None
    emprev = None
    tol = 1e-4
    while iterations:
        iterations -= 1
        P, alpha = forward(Obs, Trans, Emiss, Init)
        P2, beta = backward(Obs, Trans, Emiss, Init)

        forbackxi = alpha[:, None, :-1] * beta[None, :, 1:]
        emittedprobs = Emiss[:, Obs[1:]]
        xi = forbackxi * Trans[..., None] * emittedprobs[None, :, ...]
        xi /= xi.sum(axis=(0, 1))
        forbackga = alpha * beta
        gamma = forbackga / forbackga.sum()
        Trans = xi.sum(axis=2) / xi.sum(axis=(1, 2))
        Trans = Trans.T
        for emit in range(M):
            gammanum = gamma[:, Obs == emit]
            Emiss[:, emit] = gammanum.sum(axis=1) / gamma.sum(axis=1)
        if transprev is not None and sum(sum(abs(transprev[:]-Trans[:]))) + sum(sum(abs(emprev-Emiss))) <= tol:
            print("here", iterations)
            return Trans, Emiss
        transprev = Trans
        initprev = Init
        emprev = Emiss
        
    return Trans, Emiss

if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00],
                         [0.40, 0.50, 0.10]])
    Transition = np.array([[0.60, 0.4],
                           [0.30, 0.70]])
    Initial = np.array([0.5, 0.5])
    Hidden = [np.random.choice(2, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(2, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(3, p=Emission[s]))
    Observations = np.array(Observations)
    T_test = np.ones((2, 2)) / 2
    E_test = np.abs(np.random.randn(2, 3))
    E_test = E_test / np.sum(E_test, axis=1).reshape((-1, 1))
    T, E = baum_welch(Observations, T_test, E_test, Initial.reshape((-1, 1)))
    print(np.round(T, 2))
    print(np.round(E, 2))

here 891
[[0.81 0.19]
 [0.29 0.72]]
[[0.81 0.18 0.  ]
 [0.26 0.58 0.16]]


In [62]:
if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                         [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                         [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                         [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                         [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
    Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                           [0.20, 0.50, 0.30, 0.00, 0.00],
                           [0.01, 0.24, 0.50, 0.24, 0.01],
                           [0.00, 0.00, 0.15, 0.70, 0.15],
                           [0.00, 0.00, 0.01, 0.39, 0.60]])
    Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
    Hidden = [np.random.choice(5, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(6, p=Emission[s]))
    Observations = np.array(Observations)
    T, E = baum_welch(Observations, Transition, Emission, Initial.reshape((-1, 1)))
    print(np.round(T, 2))
    print(np.round(E, 2))

here 830
[[0.76 0.24 0.   0.   0.  ]
 [0.13 0.45 0.42 0.   0.  ]
 [0.   0.36 0.35 0.24 0.04]
 [0.   0.   0.3  0.7  0.  ]
 [0.   0.   0.05 0.   0.96]]
[[0.93 0.07 0.   0.   0.   0.  ]
 [0.37 0.63 0.   0.   0.   0.  ]
 [0.   0.   0.69 0.31 0.   0.  ]
 [0.   0.   0.   0.5  0.41 0.09]
 [0.   0.   0.   0.55 0.24 0.21]]


In [ ]:
'''
Created on Jan 26, 2012

@author: Aurelien Garivier, CNRS and Telecom ParisTech

Baum-Welch algorithm for discrete Hidden Markov models

@reference: Hidden Markov Models by Cappe, Moulines, Rydden
Springer series in statistics
see also http://www.telecom-paristech.fr/~garivier/code/index.html
'''

from random import random, choice
import numpy as np
import sys
import time
import HMM_C # needs the C functions to be compiled: use "make"

def randm(p):
    '''
    sample from discrete distribution
    in:   p = vector of probabilities, assumed to sum to 1
    '''
    res = 0
    q = p[0]
    u = random()
    while(u>q):
        res += 1
        q += p[res]
    return res

def HMMsample(nu, Q, g, n):
    '''
    sample a trajectory from a hidden markov chain
    in:   nu = initial distribution as vector of size k
      Q = transition matrix of size k
      n = positive integer
    out:  (x,y) = sample trajectory of size n of a HMM defined by (nu, Q, g):
      x = sample trajectory of size n of a Markov Chain with initial distribution nu and transition matrix Q
      y = observations such that the conditionnal distribution of y[k]
      given x[k] is g(x[k], :)
    '''
    x = np.zeros(n)
    y = np.zeros(n)
    x[0] = randm(nu)
    y[0] = randm(g[x[0], :])
    for j in range(1,n):
        x[j] = randm(Q[x[j-1], :])
        y[j] = randm(g[x[j], :])
    return (x,y)

def HMMfilter(y, nu, Q, g):
    '''
    HMM filtering of an observation sequence, given hmm parameters
    in:   y = vector of observations, assumed to be in range(g.shape[1])
      nu = initial distribution as vector of size k
      Q = transition matrix of size k x k
      g = emission matrix with k rows
    out:  phi = filter: P(x[t]=x | y[0:t]=y[0:t]) for 0<=x<k and 0<=t<n
      c(t) = conditional likelihood: P(Y[t] = y[t]| Y[0:t-1]=y[0:t-1])
    '''  
    n = y.size
    k = Q.shape[0]
    phi = np.zeros([k, n])
    c = np.zeros(n)

    Z = nu * g[:, y[0]]
    c[0] = sum(Z)
    phi[:,0] = Z/c[0]

    for t in range(1,n):
        Z = np.dot(phi[:, t-1], Q) * g[:, y[t]];
        c[t] = sum(Z)
        phi[:, t] = Z / c[t]

    return (phi,c)


def HMMsmoother(y, Q, g, c):
    '''
    HMM filtering of an observation sequence, given hmm parameters
    in:   y = vector of observations, assumed to be in range(Q.shape[0])
      Q = transition matrix of size k x k
      g = emission matrix with k rows
      c = conditional likelihoods, computed by HMMfilter
    out:  beta = smoothing factors: P(y[t+1:n]=y[t+1:n] | X[t]=x) / P(Y[t+1:n]=y[t+1:n] | Y[0:t]=y[1:t]) for 0<=x<k and 1<=t<n
      permits to compute the posterior distribution of the hidden states 
      P(X[t]=x | Y[0:n]=y[0:n])  as post = phi * beta
    '''
    n = y.size
    beta = np.ones([Q.shape[0], n])
    for t in range(n-2, -1, -1):
        beta[:,t] = np.dot(Q, g[:, y[t+1]] * beta[:, t+1]) / c[t+1]
    return beta

def HMMbaumwelch(y, nu, tol=1e-4, maxIt = 100):
    '''
    compute maximum likehood estimate using Expectation-Maximization
    iterations
    in:   y = vector of observations 
      nu = initial distribution of the hidden chain
      tol = tolerance for the stopping criterion
      maxIt = maximal number of iterations
    out:  Q = estimate of the transition matrix of the hidden markov process
      g = estimated probabilities of transition: g(x,y) = estimate of P(Y=y | X=x) for 0<=x<k
      l = log-likelihood of y for parameters Q and g  
    '''  
    global myfilter, mysmoother # should be either HMMfilter/HMMsmoother, or HMM_C.HMMfilter/HMM_C.HMMsmoother
    k = nu.size; r = 1+max(y); n = y.size
    Y = np.zeros([n, r]); 
    Y[range(n), np.int_(y)] = 1;
    Q = np.random.rand(k, k)
    g = np.random.rand(k, r)
    for j in range(k):
    Q[j,:] = Q[j,:] / sum(Q[j,:])
    g[j,:] = g[j,:] / sum(g[j,:])
    it = 0; oldQ = Q; oldg = g + tol +1

    while (sum(sum(abs(oldQ[:]-Q[:]))) + sum(sum(abs(oldg-g))) > tol) & (it<maxIt):
        it+=1
        (phi, c) = myfilter(y, nu, Q, g)
        beta = mysmoother(y, Q, g, c)
        post = phi * beta
        N = Q * (np.dot(phi[:, 0:-1], np.transpose(beta[:, 1:]*g[:, np.int_(y[1:])]/np.tile(c[1:], [k, 1]))))
        M = np.dot(post, Y)

        oldQ = Q.copy(); oldg = g.copy()
        for j in range(k):
            Q[j,:] = N[j,:] / sum(N[j,:])
            g[j,:] = M[j,:] / sum(M[j,:])
    l = sum(np.log(c))
    return (Q, g, l)


  