In [3]:
import numpy as np
import tensorflow as tf 

In [35]:
def normalization_constants(X):
    """ doc """
    return X.mean(axis=0) , X.std(axis=0)
   

In [36]:
np.random.seed(0)
a = np.random.normal(0, 2, size=(100, 1))
b = np.random.normal(2, 1, size=(100, 1))
c = np.random.normal(-3, 10, size=(100, 1))
X = np.concatenate((a, b, c), axis=1)
m, s = normalization_constants(X)
print(m)
print(s)

[ 0.11961603  2.08201297 -3.59232261]
[2.01576449 1.034667   9.52002619]


In [34]:
X.mean(axis=0) , X.std(axis=0)

(array([ 0.11961603,  2.08201297, -3.59232261]),
 array([2.01576449, 1.034667  , 9.52002619]))