In [3]:
import numpy as np
import tensorflow as tf 

In [35]:
def normalization_constants(X):
    """ doc """
    return X.mean(axis=0) , X.std(axis=0)
   

In [37]:
np.random.seed(0)
a = np.random.normal(0, 2, size=(100, 1))
b = np.random.normal(2, 1, size=(100, 1))
c = np.random.normal(-3, 10, size=(100, 1))
X = np.concatenate((a, b, c), axis=1)
m, s = normalization_constants(X)
print(m)
print(s)

[ 0.11961603  2.08201297 -3.59232261]
[2.01576449 1.034667   9.52002619]


In [34]:
X.mean(axis=0) , X.std(axis=0)

(array([ 0.11961603,  2.08201297, -3.59232261]),
 array([2.01576449, 1.034667  , 9.52002619]))

In [ ]:
def normalize(X, m, s):
    """ doc """
    return ((X - m)/s)

In [38]:
np.random.seed(0)
a = np.random.normal(0, 2, size=(100, 1))
b = np.random.normal(2, 1, size=(100, 1))
c = np.random.normal(-3, 10, size=(100, 1))
X = np.concatenate((a, b, c), axis=1)
m, s = normalization_constants(X)
print(X[:10])
#X = normalize(X, m, s)
#print(X[:10])
#m, s = normalization_constants(X)
#print(m)
#print(s)

[[  3.52810469   3.8831507   -6.69181838]
 [  0.80031442   0.65224094  -5.39379178]
 [  1.95747597   0.729515     7.99659596]
 [  4.4817864    2.96939671   3.55263731]
 [  3.73511598   0.82687659   3.40131526]
 [ -1.95455576   3.94362119 -19.16956044]
 [  1.90017684   1.58638102  -3.24326124]
 [ -0.30271442   1.25254519 -10.38030909]
 [ -0.2064377    3.92294203  -0.20075401]
 [  0.821197     3.48051479  -3.9815039 ]]


In [44]:
print(((X - m)/s)[:10])

[[ 1.69091612  1.74078977 -0.32557639]
 [ 0.33768746 -1.38186686 -0.18922943]
 [ 0.91174338 -1.3071819   1.21732003]
 [ 2.16402779  0.85765153  0.75051893]
 [ 1.79361228 -1.21308245  0.73462381]
 [-1.02897526  1.79923417 -1.63625998]
 [ 0.88331787 -0.47902557  0.03666601]
 [-0.20951378 -0.80167608 -0.71302183]
 [-0.1617519   1.77924787  0.35625623]
 [ 0.34804709  1.35164437 -0.04088028]]
