In [84]:
#!chmod +x *.py
#!cp 1-sensitivity.py 2-precision.py

In [78]:
import numpy as np
create_confusion_matrix = __import__('0-create_confusion').create_confusion_matrix

if __name__ == '__main__':
    lib = np.load('labels_logits.npz')
    labels = lib['labels']
    logits = lib['logits']

    np.set_printoptions(suppress=True)
    #confusion = create_confusion_matrix(labels, logits)
    #print(confusion)
    #np.savez_compressed('confusion.npz', confusion=confusion)
    #print(np.argmax(labels, axis=1))
    #print(np.argmax(logits, axis=1))
    
    m = labels.shape[0] # m 
    k = labels.shape[1] # Number of classes 
    result = np.zeros((k, k))
    pred =  np.argmax(logits, axis=1)
    true = np.argmax(labels, axis=1)
    for i in range(m):
        for j in range(k):
            a, b = true[i], pred[i]
            result[a][b] += 1
    confusion = (result/10)
print(confusion)

[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631.  123.   33.  163.   60.]
 [  47.   32.   87.    1.   64.   83. 4607.    0.   29.    1.]
 [  26.   95.   75.    7.   58.   18.    1. 4682.   13.  200.]
 [  31.  153.   82.  174.   27.  179.   64.    7. 4003.  122.]
 [  48.   37.   39.   71.  220.   49.    8.  244.   46. 4226.]]


In [ ]:
def compute_confusion_matrix(true, pred):
  '''Computes a confusion matrix using numpy for two np.arrays
  true and pred.

  Results are identical (and similar in computation time) to: 
    "from sklearn.metrics import confusion_matrix"

  However, this function avoids the dependency on sklearn.'''

  K = len(np.unique(true)) # Number of classes 
  result = np.zeros((K, K))

  for i in range(len(true)):
    result[true[i]][pred[i]] += 1

  return result

 true_pos = np.diag(cm) 
 precision = np.sum(true_pos / np.sum(cm, axis=0))
 recall = np.sum(true_pos / np.sum(cm, axis=1))

In [107]:
if __name__ == '__main__':
    #confusion = np.load('confusion.npz')['confusion']
    def sensitivity(confusion):
        """ doc """
        r = []
        for i in confusion:
            r.append(np.round(i.max()/i.sum(), 8))
        return(np.array(r))
    np.set_printoptions(suppress=True)
    print(sensitivity(confusion))

[0.95316302 0.96759422 0.84299517 0.84493237 0.89277629 0.80581447
 0.93051909 0.9047343  0.82672449 0.84723336]


In [121]:
import numpy as np
#precision = __import__('2-precision').precision

if __name__ == '__main__':
    #confusion = np.load('confusion.npz')['confusion']
    def precision(confusion):
        """ doc """
        true_pos = np.diag(confusion)
        return (np.round(true_pos / np.sum(confusion, axis=0), 8))
    np.set_printoptions(suppress=True)
    ##print(precision(confusion))
    true_pos = np.diag(confusion)
    print(np.round(true_pos / np.sum(confusion, axis=0), 8))

[0.93033841 0.91020543 0.87359199 0.87264628 0.88494492 0.83298922
 0.90050821 0.90648596 0.86364617 0.84503099]
