In [1]:
#!chmod +x *.py
#!cp 3-specificity.py 4-f1_score.py
from sklearn.metrics import confusion_matrix

In [2]:
def create_confusion_matrix(labels, logits):
    """ doc """
    m = labels.shape[0] # m 
    k = labels.shape[1] # Number of classes 
    y_pred = np.argmax(logits, axis=1)
    y_true = np.argmax(labels, axis=1)
    # intersect y_pred, y_true with labels, eliminate items not in labels
    ind = np.logical_and(y_pred < k, y_true < k)
    y_pred = y_pred[ind]
    y_true = y_true[ind]
    
    sample_weight = np.ones(m, dtype=np.int64)
    # also eliminate weights of eliminated items
    sample_weight = sample_weight[ind]

    # Choose the accumulator dtype to always have high precision
    if sample_weight.dtype.kind in {'i', 'u', 'b'}:
        dtype = np.int64
    else:
        dtype = np.float64

    cm = coo_matrix((sample_weight, (y_true, y_pred)),
                    shape=(k, k), dtype=dtype,
                    ).toarray()
    for i in range(m):
        a, b = y_true[i], y_pred[i]
        result[a][b] += 1
    return (result)

In [4]:
### import numpy as np
#create_confusion_matrix = __import__('0-create_confusion').create_confusion_matrix
from scipy.sparse import coo_matrix

if __name__ == '__main__':
    lib = np.load('labels_logits.npz')
    labels = lib['labels']
    logits = lib['logits']
    def create_confusion_matrix(labels, logits):
        """ doc """
        m = labels.shape[0] # m 
        k = labels.shape[1] # Number of classes 
        result = np.zeros((k, k))
        y_pred = np.argmax(logits, axis=1)
        y_true = np.argmax(labels, axis=1)
        ind = np.logical_and(y_pred < k, y_true < k)
        print(y_pred.shape)
        y_pred = y_pred[ind]
        print(y_pred.shape)
        y_true = y_true[ind]
        sample_weight = np.ones(m, dtype=np.int64)
        # also eliminate weights of eliminated items
        sample_weight = sample_weight[ind]

        for i in range(m):
            a, b = y_true[i], y_pred[i]
            result[a][b] += sample_weight[i]
        return (result)

    def one_hot(Y, classes):
        """convert an array to a one-hot matrix"""
        one_hot = np.zeros((Y.shape[0], classes))
        one_hot[np.arange(Y.shape[0]), Y] = 1
        return one_hot

    np.random.seed(2)
    """c = np.random.randint(10, 20)
    m = np.random.randint(1000, 5000)
    labels = np.random.randint(0, c, m)
    logits = np.random.randint(0, c, m)
    labels = one_hot(labels, c)
    logits = one_hot(logits, c)"""

    np.set_printoptions(suppress=True)
    confusion = create_confusion_matrix(labels, logits)
    print(confusion)
    #np.savez_compressed('confusion.npz', confusion=confusion)
    #print(np.argmax(labels, axis=1))
    #print(np.argmax(logits, axis=1))
    
    m = labels.shape[0] # m 
    k = labels.shape[1] # Number of classes 
    result = np.zeros((k, k))
    
    pred = np.argmax(logits, axis=1)
    true = np.argmax(labels, axis=1)
    # convert yt, yp into index
    #y_pred = np.array([label_to_ind.get(x, n_labels + 1) for x in y_pred])
    #y_true = np.array([label_to_ind.get(x, n_labels + 1) for x in y_true])
    
    y_pred = np.argmax(logits, axis=1)
    y_true = np.argmax(labels, axis=1)
    # intersect y_pred, y_true with labels, eliminate items not in labels
    ind = np.logical_and(y_pred < k, y_true < k)
    y_pred = y_pred[ind]
    y_true = y_true[ind]
    
    sample_weight = np.ones(m, dtype=np.int64)
    # also eliminate weights of eliminated items
    sample_weight = sample_weight[ind]

    # Choose the accumulator dtype to always have high precision
    if sample_weight.dtype.kind in {'i', 'u', 'b'}:
        dtype = np.int64
    else:
        dtype = np.float64

    cm = coo_matrix((sample_weight, (y_true, y_pred)),
                    shape=(k, k), dtype=dtype,
                    ).toarray()
    for i in range(m):
        a, b = true[i], pred[i]
        result[a][b] += sample_weight[i]

print(result)
#print(confusion_matrix(true, pred))

(50000,)
(50000,)
[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631.  123.   33.  163.   60.]
 [  47.   32.   87.    1.   64.   83. 4607.    0.   29.    1.]
 [  26.   95.   75.    7.   58.   18.    1. 4682.   13.  200.]
 [  31.  153.   82.  174.   27.  179.   64.    7. 4003.  122.]
 [  48.   37.   39.   71.  220.   49.    8.  244.   46. 4226.]]
[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631

In [6]:
#!/usr/bin/env python3

import numpy as np
create_confusion_matrix = __import__('0-create_confusion').create_confusion_matrix

def one_hot(Y, classes):
    """convert an array to a one-hot matrix"""
    one_hot = np.zeros((Y.shape[0], classes))
    one_hot[np.arange(Y.shape[0]), Y] = 1
    return one_hot

np.random.seed(2)
c = np.random.randint(10, 20)
m = np.random.randint(1000, 5000)
labels = np.random.randint(0, c, m)
logits = np.random.randint(0, c, m)
labels = one_hot(labels, c)
logits = one_hot(logits, c)
pred = np.argmax(logits, axis=1)
true = np.argmax(labels, axis=1)
print(create_confusion_matrix(labels, logits))
print("___________")
print(confusion_matrix(true, pred))

[[ 8.  9. 15.  7.  9. 12. 10. 12. 10. 15.  9. 15. 11. 15.  7. 14. 12. 13.]
 [12.  9. 13. 15. 16.  5. 16. 20.  9. 10.  8. 10.  9. 17. 20.  6. 12.  5.]
 [14.  9. 14. 12. 12.  6. 13. 10.  9.  8.  9. 11. 15. 14. 11. 10.  9. 11.]
 [ 8.  8. 12.  5.  8. 15.  5. 10. 12. 15. 12. 12.  8. 11. 13. 10.  5. 15.]
 [ 6. 15. 20. 13. 12. 10.  5.  2.  6. 14.  6.  8. 12. 13. 15. 13.  8.  9.]
 [11. 10.  9. 13.  4. 13. 11. 14.  7.  9. 15. 14.  9. 15. 10. 11. 13. 12.]
 [20.  5.  9. 14. 11. 16. 12.  6. 13.  7. 15. 11. 18.  8.  7. 14. 16.  9.]
 [15.  9.  8.  6.  9.  8. 10. 10. 11. 11. 18. 22. 12. 10.  9.  5.  7.  8.]
 [14. 12. 12. 11. 15.  6.  7.  9. 16.  8. 17.  8. 10.  9. 12.  9. 11.  8.]
 [11. 12. 15. 13. 12.  9.  4.  9. 13.  8.  9. 11. 17. 12.  3.  8. 12.  8.]
 [ 8. 11.  5.  5. 18.  4. 14. 15. 15.  8. 14. 12.  7. 19. 11. 12. 10.  9.]
 [14. 17. 10.  7. 14. 16.  9. 14.  8.  7. 11. 17. 12. 13. 10.  8. 19. 14.]
 [ 7. 10.  9.  5. 15. 15.  9. 10.  6. 13. 10. 14.  9. 14.  4. 11. 15. 18.]
 [10.  8.  9. 14. 15. 14.

In [7]:
#!/usr/bin/env python3

import numpy as np
create_confusion_matrix = __import__('0-create_confusion').create_confusion_matrix

def one_hot(Y, classes):
    """convert an array to a one-hot matrix"""
    one_hot = np.zeros((Y.shape[0], classes))
    one_hot[np.arange(Y.shape[0]), Y] = 1
    return one_hot

np.random.seed(0)
c = np.random.randint(10, 20)
m = np.random.randint(1000, 5000)
labels = np.random.randint(0, c, m)
logits = np.random.randint(0, c, m)
labels = one_hot(labels, c)
logits = one_hot(logits, c)
pred = np.argmax(logits, axis=1)
true = np.argmax(labels, axis=1)
print(create_confusion_matrix(labels, logits))
print("___________")
print(confusion_matrix(true, pred))

[[19. 23. 17. 24. 23. 18. 22. 18. 16. 20. 16. 16. 11. 22. 14.]
 [15. 14. 21. 19. 24. 20. 14. 16. 22. 23. 20. 13. 19. 26. 20.]
 [16. 17. 17. 21. 22. 14. 20. 16.  8. 24. 20. 17. 16. 28. 10.]
 [32. 26. 16. 15. 20. 18. 15. 21. 24. 20. 25. 20. 28. 18. 23.]
 [17. 22. 17. 15. 16. 21. 19. 17. 19. 21. 20. 16. 21. 14. 18.]
 [18. 15. 15. 20. 17. 24. 15. 17. 20. 26. 18. 23. 29. 16. 19.]
 [16. 20. 10. 20. 18. 13. 19. 21. 19. 19. 22. 21. 10. 23. 18.]
 [17. 20. 14. 25. 15. 17. 24. 16. 17. 19. 12. 20. 23. 17. 24.]
 [12. 22. 13. 18. 18. 20. 23. 20. 23. 16. 24. 13. 22. 16. 12.]
 [14. 29. 19. 13. 13. 21. 17. 16. 17. 26. 16. 18. 16. 21. 12.]
 [25. 22. 18. 13. 16. 16. 20. 14. 21. 22. 11. 20. 17. 30. 22.]
 [32. 23. 18. 18. 18. 27. 23. 21. 25. 17. 12. 18. 28. 19. 23.]
 [15. 19. 22. 17. 23. 11. 25. 21. 24. 17. 16. 18. 13. 15. 12.]
 [19. 16. 25. 18. 18. 18. 20. 20. 25. 22. 19. 13. 23. 17. 16.]
 [24. 19. 24. 19. 24. 16. 17. 18. 20. 16. 19. 22. 20. 14. 20.]]
___________
[[19 23 17 24 23 18 22 18 16 20 16 16 11 2

In [9]:
def compute_confusion_matrix(true, pred):
  '''Computes a confusion matrix using numpy for two np.arrays
  true and pred.

  Results are identical (and similar in computation time) to: 
    "from sklearn.metrics import confusion_matrix"

  However, this function avoids the dependency on sklearn.'''

  K = len(np.unique(true)) # Number of classes 
  result = np.zeros((K, K))

  for i in range(len(true)):
    result[true[i]][pred[i]] += 1

  return result

 true_pos = np.diag(cm) 
 precision = np.sum(true_pos / np.sum(cm, axis=0))
 recall = np.sum(true_pos / np.sum(cm, axis=1))
    
true_pos = np.diag(cm)
false_pos = np.sum(cm, axis=0) - true_pos
false_neg = np.sum(cm, axis=1) - true_pos
false_neg = np.sum(cm, axis=1) - true_pos

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 18)

In [10]:
if __name__ == '__main__':
    #confusion = np.load('confusion.npz')['confusion']
    def sensitivity(confusion):
        """ doc """
        r = []
        for i in confusion:
            r.append(np.round(i.max()/i.sum(), 8))
        return(np.array(r))
    np.set_printoptions(suppress=True)
    print(sensitivity(confusion))

[0.07389163 0.09433962 0.07614213 0.08152174 0.10695187 0.075
 0.09478673 0.11702128 0.08762887 0.09139785 0.0964467  0.08636364
 0.09278351 0.0821256  0.08510638 0.10215054 0.08133971 0.08490566]


In [11]:
import numpy as np
#precision = __import__('2-precision').precision

if __name__ == '__main__':
    #confusion = np.load('confusion.npz')['confusion']
    def precision(confusion):
        """ doc """
        true_pos = np.diag(confusion)
        return (np.round(true_pos / np.sum(confusion, axis=0), 8))
    np.set_printoptions(suppress=True)
    ##print(precision(confusion))
    true_pos = np.diag(confusion)
    print(np.round(true_pos / np.sum(confusion, axis=0), 8))

[0.03827751 0.04945055 0.07446809 0.02702703 0.05714286 0.065
 0.06521739 0.05235602 0.08421053 0.04145078 0.06896552 0.0787037
 0.04225352 0.06896552 0.07537688 0.05235602 0.03125    0.04568528]


In [26]:
np.set_printoptions(suppress=True)
confusion = create_confusion_matrix(labels, logits)
print(confusion)

(50000,)
(50000,)
[[4701.    0.   36.   17.   12.   81.   38.   11.   35.    1.]
 [   0. 5494.   36.   21.    3.   38.    7.   13.   59.    7.]
 [  64.   93. 4188.  103.  108.   17.  162.   80.  132.   21.]
 [  30.   48.  171. 4310.    2.  252.   22.   86.  128.   52.]
 [  17.   27.   35.    0. 4338.   11.   84.    9.   27.  311.]
 [  89.   57.   45.  235.   70. 3631.  123.   33.  163.   60.]
 [  47.   32.   87.    1.   64.   83. 4607.    0.   29.    1.]
 [  26.   95.   75.    7.   58.   18.    1. 4682.   13.  200.]
 [  31.  153.   82.  174.   27.  179.   64.    7. 4003.  122.]
 [  48.   37.   39.   71.  220.   49.    8.  244.   46. 4226.]]


In [112]:
def specificity(confusion):
    """ doc """
    true_pos = np.diag(confusion)
    false_pos = np.sum(confusion, axis=0) - true_pos
    false_neg = np.sum(confusion, axis=1) - true_pos
    true_neg = np.sum(confusion) - false_neg - true_pos - false_pos
    return np.round(true_neg / np.add(true_neg, false_pos), 8)
np.set_printoptions(suppress=True)
print(specificity(confusion))

[0.99218958 0.98777131 0.9865429  0.98599078 0.98750582 0.98399789
 0.98870119 0.98922476 0.98600469 0.98278237]


In [111]:
def specificity(confusion):
    """ doc """
    m = confusion.shape[0]
    r = []
    for i in range(m):
        tp = confusion[i][i]
        fn = confusion.T[i].sum()-tp
        tn = confusion.sum() - fn - tp
        allnegatives = confusion.sum() - confusion[i].sum()
        r.append(np.round(tn/allnegatives, 8))
    return np.array(r)
        
np.set_printoptions(suppress=True)
print(specificity(confusion))

[0.99731517 0.99192275 1.00386392 1.0036081  0.99904743 1.0032312
 0.99633732 1.00022309 1.00458391 0.99971119]


In [65]:
tp0 = confusion[0][0]
fn0 = confusion.T[0].sum()-tp0
tn0 = confusion.sum() - fn0 - tp0
tn0/(tn0+fn0)

0.992229409037727

In [68]:
true_pos = np.diag(confusion)
false_pos = np.sum(confusion, axis=0) - true_pos
false_neg = np.sum(confusion, axis=1) - true_pos
true_neg =  np.sum(confusion) - false_neg - true_pos
print(np.round(true_neg / (true_neg + false_pos), 8))

[0.99225011 0.98791904 0.98672159 0.98618433 0.98765999 0.98424992
 0.98882743 0.98933963 0.98619786 0.9830738 ]


In [ ]:
def perf_measure(y_actual, y_hat):
    TP = 0
    FP = 0
    TN = 0
    FN = 0

    for i in range(len(y_hat)): 
        if y_actual[i]==y_hat[i]==1:
           TP += 1
        if y_hat[i]==1 and y_actual[i]!=y_hat[i]:
           FP += 1
        if y_actual[i]==y_hat[i]==0:
            TN += 1
        if y_hat[i]==0 and y_actual[i]!=y_hat[i]:
            FN += 1

    return(TP, FP, TN, FN)

In [ ]:
def conf_mat(prob_arr, input_arr):

        # confusion matrix

        conf_arr = [[0, 0], [0, 0]]

        for i in range(len(prob_arr)):

                if int(input_arr[i]) == 1:

                        if float(prob_arr[i]) < 0.5:

                                conf_arr[0][1] = conf_arr[0][1] + 1

                        else:

                                conf_arr[0][0] = conf_arr[0][0] + 1

                elif int(input_arr[i]) == 2:

                        if float(prob_arr[i]) >= 0.5:

                                conf_arr[1][0] = conf_arr[1][0] +1

                        else:

                                conf_arr[1][1] = conf_arr[1][1] +1

        accuracy = float(conf_arr[0][0] + conf_arr[1][1])/(len(input_arr))

In [28]:
#!/usr/bin/env python3

import numpy as np
#f1_score = __import__('4-f1_score').f1_score
sensitivity = __import__('1-sensitivity').sensitivity
precision = __import__('2-precision').precision


def f1_score(confusion):
    """ doc """
    recall = sensitivity(confusion)
    pr = precision(confusion)
    return 2*((recall*pr)/(recall+pr))
if __name__ == '__main__':
    #confusion = np.load('confusion.npz')['confusion']

    np.set_printoptions(suppress=True)
    print(f1_score(confusion))

[0.94161242 0.93802287 0.8580209  0.85856574 0.88884336 0.81917654
 0.91526771 0.90560928 0.8447821  0.84613074]
